## Exercicio de Sala

In [15]:
import pandas as pd

df = pd.read_csv('Brasilia_2022.csv', delimiter=';', skiprows=8, encoding='latin1')

In [16]:
df.head()
# Exibe as 5 primeiras linhas

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2022/01/01,0000 UTC,0,884,884,"882,9",NaN,"19,2","17,4","19,2",19,"17,4","17,2",90,89,89,356.0,"4,4","1,9",NaN
1,2022/01/01,0100 UTC,",4","884,4","884,4",884,NaN,19,"17,7","19,5",19,"17,7","17,4",92,88,92,350.0,"5,2","2,1",NaN
2,2022/01/01,0200 UTC,0,"884,2","884,4","884,2",NaN,"19,1","17,6","19,1","18,8","17,7","17,6",93,91,91,6.0,"5,1","2,6",NaN
3,2022/01/01,0300 UTC,0,884,"884,2",884,NaN,"18,8","17,2","19,2","18,8","17,6","17,2",91,89,91,2.0,"5,8","2,8",NaN
4,2022/01/01,0400 UTC,0,"883,2",884,"883,2",NaN,"18,5","17,2","18,8","18,4","17,3","17,1",92,91,92,11.0,"4,3","1,3",NaN

In [19]:
df.head(10)
# Exibe as 10 primeiras linhas

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2022/01/01,0000 UTC,0,884,884,"882,9",NaN,"19,2","17,4","19,2",19,"17,4","17,2",90,89,89,356.0,"4,4","1,9",NaN
1,2022/01/01,0100 UTC,",4","884,4","884,4",884,NaN,19,"17,7","19,5",19,"17,7","17,4",92,88,92,350.0,"5,2","2,1",NaN
2,2022/01/01,0200 UTC,0,"884,2","884,4","884,2",NaN,"19,1","17,6","19,1","18,8","17,7","17,6",93,91,91,6.0,"5,1","2,6",NaN
3,2022/01/01,0300 UTC,0,884,"884,2",884,NaN,"18,8","17,2","19,2","18,8","17,6","17,2",91,89,91,2.0,"5,8","2,8",NaN
4,2022/01/01,0400 UTC,0,"883,2",884,"883,2",NaN,"18,5","17,2","18,8","18,4","17,3","17,1",92,91,92,11.0,"4,3","1,3",NaN
5,2022/01/01,0500 UTC,0,"882,8","883,2","882,8",NaN,"18,7","17,3","18,7","18,4","17,4","17,2",93,92,92,12.0,"4,7","2,9",NaN
6,2022/01/01,0600 UTC,",8","882,7","882,8","882,7",NaN,"18,3","17,4","18,7","18,3","17,4","17,3",94,92,94,350.0,"5,6","2,7",NaN
7,2022/01/01,0700 UTC,",4","882,6","882,7","882,5",NaN,"18,3","17,5","18,4","18,3","17,5","17,4",95,94,95,350.0,"6,1","3,1",NaN
8,2022/01/01,0800 UTC,0,"882,8","882,9","882,6",NaN,"18,3","17,4","18,4","18,3","17,5","17,4",95,95,95,356.0,"6,4","3,4",NaN
9,2022/01/01,0900 UTC,0,"883,3","883,3","882,8","1,5","18,3","17,5","18,3","18,2","17,5","17,4",95,95,95,2.0,"6,4","2,2",NaN

In [20]:
df.tail()
# Exibe as 5 últimas linhas

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
8755,2022/12/31,1900 UTC,0,"885,7","886,6","885,7","1563,5","23,9","18,1","24,4","22,4",19,"17,5",75,68,70,19.0,"4,2","1,9",NaN
8756,2022/12/31,2000 UTC,",2","885,7","885,8","885,6","751,9","22,8","19,6","24,7","22,7","19,6","17,8",82,67,82,27.0,"4,7",",6",NaN
8757,2022/12/31,2100 UTC,0,"886,2","886,2","885,7","226,5","22,5","17,9","23,1","22,5","20,1","17,6",85,73,75,311.0,"2,1",1,NaN
8758,2022/12/31,2200 UTC,",2","886,8","886,8","886,2","32,5","20,8","18,9","22,7","20,8","19,2","17,6",89,73,89,253.0,"1,9",",3",NaN
8759,2022/12/31,2300 UTC,0,"887,2","887,2","886,8",NaN,"20,1","18,4","20,8","19,9","18,9","18,3",91,88,90,165.0,"1,4",1,NaN

In [21]:
print(df.shape)

# Exibe o formato do DataFrame. 
# Retorna a quantidade de linhas e colunas do DataFrame em formato de tupla (linhas, colunas).

(8760, 20)

In [23]:
df.describe()

# Exibe estatísticas descritivas.
# Gera estatísticas descritivas para colunas numéricas, como contagem, média, desvio padrão, valores mínimo e máximo, e quartis.

,UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))",Unnamed: 19
count,8760.000000,8760.000000,8760.000000,8759.000000,0.0
mean,66.591781,60.413813,63.533219,154.376527,NaN
std,20.634391,20.996270,20.915054,104.721595,NaN
min,13.000000,12.000000,13.000000,1.000000,NaN
25%,51.000000,44.000000,47.000000,82.000000,NaN
50%,69.000000,61.000000,65.000000,113.000000,NaN
75%,85.000000,78.000000,82.000000,235.500000,NaN
max,96.000000,96.000000,96.000000,360.000000,NaN

In [25]:
df.dtypes

# Exibe os tipos de dados das colunas

Data                                                      object
Hora UTC                                                  object
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                          object
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)     object
PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)           object
PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)          object
RADIACAO GLOBAL (Kj/m²)                                   object
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)              object
TEMPERATURA DO PONTO DE ORVALHO (°C)                      object
TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)                object
TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)                object
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)          object
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)          object
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                   int64
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                   int64
UMIDADE RELATIVA DO AR, HORARIA (%)                        int64
VENTO, DIREÇÃO HORARIA (gr) (° (gr))                     float64
VENTO, RAJADA MAXIMA (m/s)                                object
VENTO, VELOCIDADE HORARIA (m/s)                           object
Unnamed: 19                                              float64
dtype: object

In [53]:
# sample(): Seleciona uma amostra aleatória de linhas do DataFrame.

# Seleciona 5 linhas aleatórias
df.sample(n=5)

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
5743,2022/08/28,0700 UTC,0,"887,9","888,1","887,9",NaN,"16,8","8,9","16,8","14,7","8,9","7,8",66,58,60,123.0,"2,7","1,4",NaN
6443,2022/09/26,1100 UTC,0,"889,7","889,7",889,1096,"20,3","15,7","20,3","19,6",16,"15,5",80,74,75,57.0,"7,6","3,8",NaN
4567,2022/07/10,0700 UTC,0,"889,8","890,1","889,8",NaN,"16,4","7,2","16,7","16,1","7,9","7,1",57,53,54,79.0,"3,8","1,9",NaN
7140,2022/10/25,1200 UTC,0,"887,2","887,3","887,1","2373,7","24,1","14,8","24,8",22,"15,8","14,8",66,55,56,22.0,5,2,NaN
1379,2022/02/27,1100 UTC,0,"888,1","888,1","887,3","957,1","22,3","15,9","22,4","20,7","16,6","15,5",77,66,67,75.0,"7,6","3,2",NaN

In [57]:
# Selecionar colunas específicas
df_reduzido = df[['Data', 'Hora UTC', 'RADIACAO GLOBAL (Kj/m²)']]

df_reduzido.head()

         Data  Hora UTC RADIACAO GLOBAL (Kj/m²)
0  2022/01/01  0000 UTC                     NaN
1  2022/01/01  0100 UTC                     NaN
2  2022/01/01  0200 UTC                     NaN
3  2022/01/01  0300 UTC                     NaN
4  2022/01/01  0400 UTC                     NaN

In [59]:
# Selecionar 1000 linhas aleatórias
df_reduzido = df_reduzido.sample(n=1000, random_state=42)

df_reduzido

            Data  Hora UTC RADIACAO GLOBAL (Kj/m²)
8046  2022/12/02  0600 UTC                     NaN
3910  2022/06/12  2200 UTC                     NaN
411   2022/01/18  0300 UTC                     NaN
3146  2022/05/12  0200 UTC                     NaN
8664  2022/12/28  0000 UTC                     NaN
...          ...       ...                     ...
6152  2022/09/14  0800 UTC                     NaN
7550  2022/11/11  1400 UTC                  2184,5
8476  2022/12/20  0400 UTC                     NaN
828   2022/02/04  1200 UTC                   307,6
6266  2022/09/19  0200 UTC                     NaN

[1000 rows x 3 columns]

In [49]:
# Exibe os nomes das colunas
df.columns

Index(['Data', 'Hora UTC', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)',
       'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)',
       'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)',
       'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)',
       'RADIACAO GLOBAL (Kj/m²)',
       'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)',
       'TEMPERATURA DO PONTO DE ORVALHO (°C)',
       'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)',
       'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)',
       'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)',
       'UMIDADE RELATIVA DO AR, HORARIA (%)',
       'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)',
       'VENTO, VELOCIDADE HORARIA (m/s)', 'Unnamed: 19'],
      dtype='object')

In [62]:
coluna1 = df['UMIDADE RELATIVA DO AR, HORARIA (%)']
coluna1

# Funções para calcular o valor mínimo, máximo, soma e média

# Valor mínimo
minimo = df['UMIDADE RELATIVA DO AR, HORARIA (%)'].min()

# Valor máximo
maximo = df['UMIDADE RELATIVA DO AR, HORARIA (%)'].max()

# Soma dos valores
soma = df['UMIDADE RELATIVA DO AR, HORARIA (%)'].sum()

# Média dos valores
media = df['UMIDADE RELATIVA DO AR, HORARIA (%)'].mean()

print(f"Mínimo: {minimo}, Máximo: {maximo}, Soma: {soma}, Média: {media} da Umidade Relativa do Ar.")

Mínimo: 13, Máximo: 96, Soma: 556551, Média: 63.53321917808219 da Umidade Relativa do Ar.

In [81]:
coluna_temperatura_maxima = df['TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)'].max()

coluna_temperatura_maxima = pd.to_numeric(df['TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)'], errors='coerce')
coluna_temperatura_maxima

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
8755   NaN
8756   NaN
8757   NaN
8758   NaN
8759   NaN
Name: TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C), Length: 8760, dtype: float64

In [68]:
#Identifica valores nulos no DataFrame, retornando um DataFrame booleano.

# Verifica valores nulos
nulos = df.isnull()
nulos

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
8756,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
8757,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
8758,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
8759,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True

In [69]:
# Contagem de valores nulos em cada coluna
nulos_por_coluna = df.isnull().sum()
nulos_por_coluna

Data                                                        0
Hora UTC                                                    0
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                            1
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)       0
PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)             0
PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)            0
RADIACAO GLOBAL (Kj/m²)                                  4082
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)                0
TEMPERATURA DO PONTO DE ORVALHO (°C)                        0
TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)                  0
TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)                  0
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)            0
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)            0
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                    0
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                    0
UMIDADE RELATIVA DO AR, HORARIA (%)                         0
VENTO, DIREÇÃO HORARIA (gr) (° (gr))                        1
VENTO, RAJADA MAXIMA (m/s)                                  0
VENTO, VELOCIDADE HORARIA (m/s)                             0
Unnamed: 19                                              8760
dtype: int64

In [87]:
# Remove linhas com qualquer valor nulo
df_sem_nulos = df.dropna()
df_sem_nulos

# Remove colunas que contenham valores nulos
df_sem_nulos_colunas = df.dropna(axis=1, how='all')
df_sem_nulos_colunas

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,2022/01/01,0000 UTC,0,884,884,"882,9",NaN,"19,2","17,4","19,2",19,"17,4","17,2",90,89,89,356.0,"4,4","1,9"
1,2022/01/01,0100 UTC,",4","884,4","884,4",884,NaN,19,"17,7","19,5",19,"17,7","17,4",92,88,92,350.0,"5,2","2,1"
2,2022/01/01,0200 UTC,0,"884,2","884,4","884,2",NaN,"19,1","17,6","19,1","18,8","17,7","17,6",93,91,91,6.0,"5,1","2,6"
3,2022/01/01,0300 UTC,0,884,"884,2",884,NaN,"18,8","17,2","19,2","18,8","17,6","17,2",91,89,91,2.0,"5,8","2,8"
4,2022/01/01,0400 UTC,0,"883,2",884,"883,2",NaN,"18,5","17,2","18,8","18,4","17,3","17,1",92,91,92,11.0,"4,3","1,3"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022/12/31,1900 UTC,0,"885,7","886,6","885,7","1563,5","23,9","18,1","24,4","22,4",19,"17,5",75,68,70,19.0,"4,2","1,9"
8756,2022/12/31,2000 UTC,",2","885,7","885,8","885,6","751,9","22,8","19,6","24,7","22,7","19,6","17,8",82,67,82,27.0,"4,7",",6"
8757,2022/12/31,2100 UTC,0,"886,2","886,2","885,7","226,5","22,5","17,9","23,1","22,5","20,1","17,6",85,73,75,311.0,"2,1",1
8758,2022/12/31,2200 UTC,",2","886,8","886,8","886,2","32,5","20,8","18,9","22,7","20,8","19,2","17,6",89,73,89,253.0,"1,9",",3"
8759,2022/12/31,2300 UTC,0,"887,2","887,2","886,8",NaN,"20,1","18,4","20,8","19,9","18,9","18,3",91,88,90,165.0,"1,4",1

In [83]:
# Preenche valores nulos com um valor específico.

# Preenche valores nulos com 0
df_preenchido = df.fillna(0)
df_preenchido

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2022/01/01,0000 UTC,0,884,884,"882,9",0,"19,2","17,4","19,2",19,"17,4","17,2",90,89,89,356.0,"4,4","1,9",0.0
1,2022/01/01,0100 UTC,",4","884,4","884,4",884,0,19,"17,7","19,5",19,"17,7","17,4",92,88,92,350.0,"5,2","2,1",0.0
2,2022/01/01,0200 UTC,0,"884,2","884,4","884,2",0,"19,1","17,6","19,1","18,8","17,7","17,6",93,91,91,6.0,"5,1","2,6",0.0
3,2022/01/01,0300 UTC,0,884,"884,2",884,0,"18,8","17,2","19,2","18,8","17,6","17,2",91,89,91,2.0,"5,8","2,8",0.0
4,2022/01/01,0400 UTC,0,"883,2",884,"883,2",0,"18,5","17,2","18,8","18,4","17,3","17,1",92,91,92,11.0,"4,3","1,3",0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022/12/31,1900 UTC,0,"885,7","886,6","885,7","1563,5","23,9","18,1","24,4","22,4",19,"17,5",75,68,70,19.0,"4,2","1,9",0.0
8756,2022/12/31,2000 UTC,",2","885,7","885,8","885,6","751,9","22,8","19,6","24,7","22,7","19,6","17,8",82,67,82,27.0,"4,7",",6",0.0
8757,2022/12/31,2100 UTC,0,"886,2","886,2","885,7","226,5","22,5","17,9","23,1","22,5","20,1","17,6",85,73,75,311.0,"2,1",1,0.0
8758,2022/12/31,2200 UTC,",2","886,8","886,8","886,2","32,5","20,8","18,9","22,7","20,8","19,2","17,6",89,73,89,253.0,"1,9",",3",0.0
8759,2022/12/31,2300 UTC,0,"887,2","887,2","886,8",0,"20,1","18,4","20,8","19,9","18,9","18,3",91,88,90,165.0,"1,4",1,0.0

In [89]:
# Substitui todos os valores 0 por NaN
df_substituido = df.replace('0', 'NaN')
df_substituido

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2022/01/01,0000 UTC,NaN,884,884,"882,9",NaN,"19,2","17,4","19,2",19,"17,4","17,2",90,89,89,356.0,"4,4","1,9",NaN
1,2022/01/01,0100 UTC,",4","884,4","884,4",884,NaN,19,"17,7","19,5",19,"17,7","17,4",92,88,92,350.0,"5,2","2,1",NaN
2,2022/01/01,0200 UTC,NaN,"884,2","884,4","884,2",NaN,"19,1","17,6","19,1","18,8","17,7","17,6",93,91,91,6.0,"5,1","2,6",NaN
3,2022/01/01,0300 UTC,NaN,884,"884,2",884,NaN,"18,8","17,2","19,2","18,8","17,6","17,2",91,89,91,2.0,"5,8","2,8",NaN
4,2022/01/01,0400 UTC,NaN,"883,2",884,"883,2",NaN,"18,5","17,2","18,8","18,4","17,3","17,1",92,91,92,11.0,"4,3","1,3",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022/12/31,1900 UTC,NaN,"885,7","886,6","885,7","1563,5","23,9","18,1","24,4","22,4",19,"17,5",75,68,70,19.0,"4,2","1,9",NaN
8756,2022/12/31,2000 UTC,",2","885,7","885,8","885,6","751,9","22,8","19,6","24,7","22,7","19,6","17,8",82,67,82,27.0,"4,7",",6",NaN
8757,2022/12/31,2100 UTC,NaN,"886,2","886,2","885,7","226,5","22,5","17,9","23,1","22,5","20,1","17,6",85,73,75,311.0,"2,1",1,NaN
8758,2022/12/31,2200 UTC,",2","886,8","886,8","886,2","32,5","20,8","18,9","22,7","20,8","19,2","17,6",89,73,89,253.0,"1,9",",3",NaN
8759,2022/12/31,2300 UTC,NaN,"887,2","887,2","886,8",NaN,"20,1","18,4","20,8","19,9","18,9","18,3",91,88,90,165.0,"1,4",1,NaN